# Settings for the app
app:
  # HTML Title
  title: WALKscope Denver
  # Header name
  name: WALKscope
  # Meta description that will show up in Google search results
  meta_description: _(Shareabouts is a mapping tool to gather crowd sourced public input. Use it to collect suggested locations and comments in a social, engaging process.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 39.7474
      lng: -104.9777
    zoom: 14
    minZoom: 10
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
    - url: /static/data/philadelphia.geojson
      type: json
      rules:
        - condition: 'true'
          style:
            color: "#444"
            opacity: 0.6
            fillOpacity: 0.1
            weight: 1

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  peds:
    label: _(Pedestrian Counts)
    rules:
      - condition: '"{{location_type}}" === "peds"'
        # Display landmarks as icons

        icon:
          iconUrl: /static/css/images/feature-point-brick.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/marker-focused-brick.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

        # style:
        #   color: '#0d85e9'
        #   radius: 8
        #   weight: 1
        #   opacity: 0.9
        #   fillOpacity: 0.4
        # focus_style:
        #   color: '#0d85e9'
        #   radius: 16
        #   weight: 1
        #   opacity: 0.9
        #   fillOpacity: 0.4

  intersection:
    label: _(Intersection Quality)
    rules:
      - condition: '"{{location_type}}" === "intersection"'
        # Show parks that are points as icons...

        icon:
          iconUrl: /static/css/images/feature-point-pumpkin.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/marker-focused-pumpkin.png
          shadowUrl: /static/css/images/marker-shadow.png
          # iconSize: [25, 41]
          #shadowSize: [41, 41]
          # iconAnchor: [12, 41]

        # ...and parks that are polygons as shapes.

        style:
          color: '#4bbd45'
          radius: 8
          weight: 1
          opacity: 0.9
          fillOpacity: 0.4
        focus_style:
          color: '#4bbd45'
          radius: 16
          weight: 1
          opacity: 0.9
          fillOpacity: 0.4

  street:
    label: _(Street Quality)
    rules:
      - condition: '"{{location_type}}" === "street"'
 
        icon:
          iconUrl: /static/css/images/feature-point-navy.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/marker-focused-navy.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]


        style:
          color: '#f95016'
          radius: 8
          weight: 4
          opacity: 0.9
          fillOpacity: 0.4
        focus_style:
          color: '#f95016'
          radius: 16
          weight: 4
          opacity: 0.9
          fillOpacity: 0.4
      - condition: '"{{location_type}}" === "school"'
        style:
          color: '#f95016'
          radius: 8
          weight: 1
          opacity: 0.9
          fillOpacity: 0.4
        focus_style:
          color: '#f95016'
          radius: 16
          weight: 1
          opacity: 0.9
          fillOpacity: 0.4


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Place)
  action_text: _(added)
  # title: _(Add a place...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - prompt: _(What would you like to record?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Number of Pedestrians)
          value: peds
        - label: _(Street Quality)
          value: street
        - label: _(Intersection Quality)
          value: intersection
      name: location_type
      attrs:
        - key: required
# Ped Count
    - prompt: _(How many people excluding you are currently on this street segment)
      type: text
      name: num_peds
      optional: false
      attrs:
        - key: placeholder
          value: _(Number of Peds)
        - key: size
          value: 15
        - key: class
          value: peds-input
    - prompt: _(What's the temperature like?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Warm (80° or more))
          value: warm
        - label: _(Mild (40-80°))
          value: mild
        - label: _(Cold (40°or less))
          value: cold
      name: temp
      attrs:
        - key:  required
        - key: class
          value: peds-input
    - prompt: _(Is it raining or snowing?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Raining)
          value: raining
        - label: _(Snowing)
          value: snowing
        - label: _(Neither)
          value: neither
      name: precip
      attrs:
        - key: required
        - key: class
          value: peds-input
    - prompt: _(How long did you observe this street segment?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Less than 15 minutes)
          value: 0-15
        - label: _(15-30 minutes)
          value: 15-30
        - label: _(30-45 minutes)
          value: 30-45
        - label: _(45-60 minutes)
          value: 45-60
        - label: _(More than 60 minutes)
          value: 60+           
      name: duration
      attrs:
        - key: required
        - key: class
          value: peds-input
# Intersection Quality 
    - prompt: _(How many lanes are there to cross (see tips)?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(1)
          value: 1
        - label: _(2)
          value: 2
        - label: _(3)
          value: 3
        - label: _(4)
          value: 4
        - label: _(5)
          value: 5 
        - label: _(6)
          value: 6
        - label: _(7)
          value: 7
        - label: _(8)
          value: 8
        - label: _(9)
          value: 9
        - label: _(10)
          value: 10  
        - label: _(11)
          value: 11
        - label: _(12)
          value: 12
        - label: _(13)
          value: 13                     
        - label: _(14)
          value: 14  
      name: num_lanes
      attrs:
        - key: required
        - key: class
          value: intersection-input
    - prompt: _(Are there painted crosswalks?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Yes)
          value: yes
        - label: _(No)
          value: no     
      attrs:
        - key: required
        - key: class
          value: intersection-input                 
    - prompt: _(Are there median islands or bulb-outs?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Yes, median islands)
          value: medianislands
        - label: _(Yes, bulb-outs)
          value: bulbouts                      
        - label: _(Yes, Both)
          value: both 
        - label: _(No)
          value: no   
      name: intersection_islands
      attrs:
        - key: required 
        - key: class
          value: intersection-input
    - prompt: _(Are there stop signs?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Yes, two way stop signs)
          value: twoway
        - label: _(Yes, all way stop signs)
          value: allway                      
        - label: _(No)
          value: no  
      name: intersection_stopsigns
      attrs:
        - key: required 
        - key: class
          value: intersection-input
    - prompt: _(Are there traffic lights and/or pedestrian crossing signals?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Yes, traffic lights only)
          value: lights  
        - label: _(Yes, pedestrian crossing signals only)
          value: pedsignals        
        - label: _(Yes, traffic lights and pedestrian crossing signals)
          value: lights_pedsignals
        - label: _(No)
          value: no                            
      name: intersection_lightspedsignals
      attrs:
        - key: required 
        - key: class
          value: intersection-input
    - prompt: _(Are drivers generally obeying stop signs?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Yes)
          value: yes
        - label: _(No)
          value: no     
      name: intersection_drivers_stopsigns
      attrs:
        - key: required    
        - key: class
          value: intersection-input
    - prompt: _(Are drivers generally following speed limits?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Yes)
          value: yes
        - label: _(No)
          value: no     
      name: intersection_drivers_speed
      attrs:
        - key: required
        - key: class
          value: intersection-input
    - prompt: _(Are drivers generally yielding to pedestrians?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Yes)
          value: yes
        - label: _(No)
          value: no     
      name: intersection_drivers_yield
      attrs:
        - key: required    
        - key: class
          value: intersection-input         
    - prompt: _(Roughly how many pedestrians do you see?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(1-5)
          value: 1-5
        - label: _(6-15)
          value: 6-15
        - label: _(16+)
          value: 16+
        - label: _(None)
          value: None
      name: intersection_numpeds
      attrs:
        - key: required     
        - key: class
          value: intersection-input   

# Street Questions
    - prompt: _(What type of sidewalk?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(No sidewalk)
          value: no_sidewalk
        - label: _(Less than 2 feet attached)
          value: less_2ft_attached
        - label: _(2-3 feet attached)
          value: 2to3_attached
        - label: _(5 ft attached)
          value: 5_attached
      name: street_type
      attrs:
        - key: required     
        - key: class
          value: street-input 
    - prompt: _(Are there obstructions in the sidewalk?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Yes)
          value: yes
        - label: _(No)
          value: no       
      name: street_obst
      attrs:
        - key: required     
        - key: class
          value: street-input 
    - prompt: _(Is the sidewalk significantly cracked or uneven?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Yes)
          value: yes
        - label: _(No)
          value: no       
      name: street_crack
      attrs:
        - key: required     
        - key: class
          value: street-input
    - prompt: _(Do you feel unsafe because of poor visibility or lighting?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Yes)
          value: yes
        - label: _(No)
          value: no       
      name: street_light
      attrs:
        - key: required     
        - key: class
          value: street-input
    - prompt: _(Do you feel unsafe because of a high volume or high speed traffic?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(Yes)
          value: yes
        - label: _(No)
          value: no       
      name: street_traffic
      attrs:
        - key: required     
        - key: class
          value: street-input
    - prompt: _(Are there other safety concerns?)
      type: text
      name: street_safety
      attrs:
        - key: placeholder
          value: _(run-down buildings, etc)
        - key: size
          value: 30  
        - key: class
          value: street-input
# Common Fields   
    - prompt: _(How would you rate the pedestrian quality overall?)
      type: select
      options:
        - label: _(...)
          value: ''
        - label: _(1)
          value: 1
        - label: _(2)
          value: 2
        - label: _(3)
          value: 3
        - label: _(4)
          value: 4
        - label: _(5)
          value: 5 
        - label: _(6)
          value: 6
        - label: _(7)
          value: 7
        - label: _(8)
          value: 8
        - label: _(9)
          value: 9
        - label: _(10)
          value: 10  
      attrs:
        - key: class
          value: opt-input      
    - prompt: _(Image)
      inputfile_label: _(Add an Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*
        - key: class
          value: opt-input
    - prompt: _(Description)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(If you like, describe the location...)
        - key: size
          value: 280
        - key: class
          value: opt-input
    - prompt: _(Email)
      type: text
      name: submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Email)
        - key: size
          value: 30
        - key: class
          value: opt-input

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(Instructions)
    slug: instructions
    name: overview
    start_page: true

  - title: _(About)
    slug: why
    url: /static/pages/why.html

  - title: _(Tips)
    slug: tips
    url: /static/pages/tips.html

  # - title: _(GitHub)
    # external: true
    # url: https://github.com/openplans/shareabouts
