# Settings for the app
app:
  # HTML Title
  title: Bike Parking Survey
  # Header name
  name: Bike Parking Survey
  # Meta description that will show up in Google search results
  meta_description: The Bike Parking Survey is a way to crowdsource bike parking availability at local train stations.


# Settings for map and layer configs
map:
  options:
    center:
      lat: 39.9523524
      lng: -75.1636075
    zoom: 12
    minZoom: 10
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types: {
  Regional Rail Station: {
    default: blue,
    focused: red
  }
}

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons: {
  blue: {
    iconUrl: /static/css/images/feature-point.png,
    iconSize: { width: 17, height: 18 },
    iconAnchor: { x: 9, y: 9 },
    popupAnchor: { x: 9, y: 9 }
  },
  red: {
    iconUrl: /static/css/images/marker-focused.png,
    shadowUrl: /static/css/images/marker-shadow.png,
    iconSize: { width: 25, height: 41 },
    shadowSize: { width: 41, height: 41 },
    iconAnchor: { x: 12, y: 41 },
    popupAnchor: { x: 12, y: 6 }
  }
}

place:
  adding_supported: false
  add_button_label: Add an Place
  action_text: created
  anonymous_name: Someone
  submit_button_label: Submit

survey: {
  submission_type: surveys,

  # Response display config
  show_responses: true,
  response_name: bike parking estimate,
  response_plural_name: bike parking estimate,
  action_text: estimated the bike parking at,
  anonymous_name: Someone,

  # Survey form config
  title: Tell us about this station,
  form_link_text: "How many bikes can park here?",
  submit_btn_text: Submit,
  items: [
    {
      prompt: "How many bicycles can park at this station?",
      label: bikes,
      type: text,
      name: parking_count,
      attrs: [
        { key: placeholder, value: "#"}
      ]
    }, {
      prompt: Your Name,
      label: Name,
      type: text,
      name: submitter_name,
      optional: true
    },
    {
      prompt: Comment,
      label: Comment,
      type: textarea,
      name: comment,
      optional: true
    }
  ]
}

support: {
  submission_type: support,

  submit_btn_text: I'd park my bike here!,
  action_text: wants to park a bike at,
  anonymous_name: Someone
}

pages:
  - title: About
    slug: about
    name: overview
    start_page: true
  - title: Download
    pages:
      - title: Station Data
        external: true
        url: /download/places.csv
      - title: Parking Data
        external: true
        url: /download/surveys.csv
