# Settings for the app
app:
  # HTML Title
  title: Jackson Heights Survey
  # Header name
  name: Jackson Heights Survey
  # Meta description that will show up in Google search results
  meta_description: The neighbors of Jackson Heights are collecting valuable information give us a better understanding about our local problems and opportunities so we can advocate for a better neighborhood!

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat:  40.755595
      lng: -73.885889
    zoom: 15
    minZoom: 11
    maxZoom: 17
    maxBounds: [[40.725, -73.93], [40.785, -73.8]]
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Idea:
    default: tick
    focused: tickselected
  Problem:
    default: cross
    focused: crossselected

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  tick:
    iconUrl: /static/css/images/tick.png
    iconSize:
      width: 32
      height: 32
    iconAnchor:
      x: 16
      y: 30
  cross:
    iconUrl: /static/css/images/cross.png
    iconSize:
      width: 24
      height: 24
    iconAnchor:
      x: 12
      y: 22
  tickselected:
    iconUrl: /static/css/images/marker-tick.png
    iconSize:
      width: 25
      height: 41
    iconAnchor:
      x: 12
      y: 41
  crossselected:
    iconUrl: /static/css/images/marker-cross.png
    iconSize:
      width: 25
      height: 41
    iconAnchor:
      x: 12
      y: 41

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true

place:
  adding_supported: true
  add_button_label: Add a Place
  title: Tell us more...
  action_text: added
  anonymous_name: Someone
  submit_button_label: Submit
  items:
    - prompt: Place Name
      type: text
      name: name
      attrs:
        - key: placeholder
          value: Location Name
        - key: size
          value: 30
    - prompt: Place Type
      type: select
      options:
        - Idea
        - Problem
      name: location_type
    - prompt: Description
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: Description...
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: Name
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response display config
  show_responses: true
  response_name: comment
  response_plural_name: comments
  action_text: commented on
  anonymous_name: Someone

  # Survey form config
  title: Leave a Comment
  form_link_text: Leave a Comment
  submit_btn_text: Comment
  items:
    - prompt: Leave Comment
      label: Comment
      type: textarea
      name: comment
    - prompt: Your Name
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: "supported"
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    start_page: true
  - title: JHGB
    external: true
    url: http://www.jhbg.org
  - title: Download the Data!
    external: true
    url: /download/places.csv
