# Settings for the app
app:
  # HTML Title
  title: Sister Cities Park Survey
  # Header name
  name: Sister Cities Park Survey
  # Meta description that will show up in Google search results
  meta_description: The Sister Cities Park Survey is demonstration of how Shareabouts can be used to collect important data about park usage, leading to a better park for all.


# Settings for map and layer configs
map:
  options:
    center:
      lat: 39.957833
      lng: -75.169379
    zoom: 20
    minZoom: 19
    maxZoom: 20
    maxBounds: [[39.956, -75.172], [39.960, -75.166]]
  base_layer:
    url: /static/tiles/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. Tiles by <a href="http://openplans.org">OpenPlans</a>.'
    maxZoom: 20
    tms: true
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Cafe:
    default: bigplus
    focused: bigplusselected
  Garden:
    default: bigplus
    focused: bigplusselected
  Lawn:
    default: bigplus
    focused: bigplusselected
  Park Bench:
    default: bigplus
    focused: bigplusselected
  Water:
    default: bigplus
    focused: bigplusselected

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  bigplus:
    iconUrl: /static/css/images/marker-sister-cities.png
    iconSize:
      width: 130
      height: 130
    iconAnchor:
      x: 65
      y: 65
    popupAnchor:
      x: 65
      y: 65
  bigplusselected:
    iconUrl: /static/css/images/marker-sister-cities-selected.png
    iconSize:
      width: 130
      height: 130
    iconAnchor:
      x: 65
      y: 65
    popupAnchor:
      x: 65
      y: 65


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: false

place:
  adding_supported: false
  add_button_label: Add an Place
  title: Add a part of the park to survey
  action_text: updated
  anonymous_name: Someone
  submit_button_label: Submit
  items:
    - prompt: Name
      type: text
      name: name
      attrs:
        - key: placeholder
          value: Location Name
        - key: size
          value: 30
    - prompt: Type
      type: select
      options:
        - Cafe
        - Garden
        - Lawn
        - Park Bench
        - Water
      name: location_type
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: Name
        - key: size
          value: 30
    - prompt: Description
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: Description...

survey:
  submission_type: surveys

  # Response display config
  pretty_datetime_format: MMM D \at h:mm a
  show_responses: true
  response_name: survey
  response_plural_name: surveys
  action_text: surveyed
  anonymous_name: Someone

  # Survey form config
  title: Record Usage
  form_link_text: Record Usage
  submit_btn_text: Submit
  items:
    - prompt: How many people are using this space right now?
      type: text
      name: usage
      label: People Count
      attrs:
        - key: placeholder
          value: '#'
        - key: size
          value: 30
    - prompt: What are they doing?
      type: textarea
      name: description
      label: Description
      optional: true
      attrs:
        - key: placeholder
          value: Description...
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: Name
        - key: size
          value: 30

support:
  submission_type: support
  submit_btn_text: Support This!
  action_text: supported
  anonymous_name: Someone

pages:
  - title: Instructions
    slug: instructions
    start_page: true

  - title: Download Surveys
    external: true
    url: /download/surveys.csv
