# Settings for the app
app:
  # HTML Title
  title: Mansfield Tomorrow | Mapping Places to Preserve and Change
  # Header name
  #name: Mansfield Tomorrow
  # Meta description that will show up in Google search results
  meta_description: _(Mansfield Tomorrow is a process for planning the future of Mansfield. This map is a tool to add places you want to preserve and change. It is powered by Shareabouts, a mapping tool to gather public input. Use it to collect suggested locations and comments in a social, engaging process.)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 41.801447
      lng: -72.242585
    zoom: 14
    minZoom: 1
    maxZoom: 17
  base_layer:
    #url: http://gisprpxy.itd.state.ma.us/arcgisserver/rest/services/Basemaps/MassGISBasemapWithLabels2/MapServer/tile/{z}/{y}/{x}
    #url: http://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}.png
    #url: http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.png
    #url: http://services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers:
    - id: 'townboundary'
      url: '/static/layers/mansfield_ct.geojson'
      type: 'json'
      visible: true
      rules:
        - condition: 'true'
          style:
            color: '#000'
            opacity: 0.9
            fillOpacity: 0
            weight: 2

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  Place you want to preserve:
    default: green_feature
    focused: green_focused
    label: _(place to preserve)
  General comment:
    default: yellow_feature
    focused: yellow_focused
    label: _(comment on a place)
  Place you want to change:
    default: red_feature
    focused: red_focused
    label: _(place to change)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  yellow_feature:
    iconUrl: /static/css/images/feature-point-yellow.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red_feature:
    iconUrl: /static/css/images/feature-point-red.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  green_feature:
    iconUrl: /static/css/images/feature-point-green.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  yellow_focused:
    iconUrl: /static/css/images/marker-focused-yellow.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  red_focused:
    iconUrl: /static/css/images/marker-focused-red.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  green_focused:
    iconUrl: /static/css/images/marker-focused-green.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Place)
  action_text: _(added)
  title: _(Tell us about this place...)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Save)
  items:
    - prompt: _(Place Name)
      name: name
      type: text
      optional: false
      attrs:
        - key: placeholder
          value: _(Place Name)
    - prompt: _(Place Type)
      name: location_type
      type: select
      options:
        - Please select
        - Place you want to preserve
        - Place you want to change
        - General comment
    - prompt: _(Description)
      type: textarea
      name: description
      optional: false
      attrs:
        - key: placeholder
          value: _(Tell us more about this location...)
        - key: rows
          value: 3
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - inputfile_label: _(Add an Image)
      type: file
      name: my_image
      attrs:
        - key: accept
          value: image/*

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
          value: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      attrs:
        - key: required
          value: required

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    url: /static/pages/about.html
    start_page: true
  - title: MansfieldTomorrow.com
    url: http://www.mansfieldtomorrow.com/
    external: true
