# Settings for the app
app:
  # HTML Title
  title: Walk Philly | Mapping Pedestrian Obstacles
  # Header name
  name: Walk Philly
  # Meta description that will show up in Google search results
  meta_description: _(Walk Philly is a tool to crowdsource pedestrian obstacles in Philadelphia. It is powered by Shareabouts, a mapping tool to gather public input. Use it to collect suggested locations and comments in a social, engaging process.)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 39.9523524
      lng: -75.1636075
    zoom: 14
    minZoom: 10
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  obstacle:
    default: dot
    focused: marker
    label: _(obstacle)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  dot:
    iconUrl: /static/css/images/markers/dot-744edc.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  marker:
    iconUrl: /static/css/images/markers/marker-744edc.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Report an Obstacle)
  action_text: _(added)
  title: _(Snap a photo of the pedestrian obstacle...)
  action_text: _(reported)
  anonymous_name: _(Someone)
  submit_button_label: _(Save)
  items:
    - name: location_type
      type: hidden
      attrs:
        - key: value
          value: obstacle
    - inputfile_label: _(Add an Image)
      type: file
      name: my_image
      attrs:
        - key: accept
          value: image/*
        - key: required
          value: required
    - prompt: _(Description)
      type: text
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description)
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
          value: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      attrs:
        - key: required
          value: required

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    start_page: true
