# Settings for the app
app:
  # HTML Title
  title: Bike to Transit Stations Survey
  # Header name
  name: Bike to Transit Stations Survey
  # Meta description that will show up in Google search results
  meta_description: The Bicycle Coalition of Greater Philadelphia, SEPTA, NJ Transit, PATCO, DVRPC, and Open Plans are collaborating to determine how transit stations can better accommodate bicyclists. This map will help identify where the demand for better bicycle facilities is greatest.


# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 39.9368556899583
      lng: -75.20330429077147
    zoom: 13
    minZoom: 10
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  SEPTA Transportation Center:
    default: yellow-dot
    focused: yellow-pin
  Light Rail Transit:
    default: river-dot
    focused: river-pin
  NJ Transit:
    default: nj-dot
    focused: nj-pin
  PATCO:
    default: red-dot
    focused: red-pin
  Surface Trolley:
    default: green-dot
    focused: green-pin
  SEPTA Regional Rail:
    default: gray-dot
    focused: gray-pin
  Rapid Transit:
    default: purple-dot
    focused: purple-pin
  Subway-Elevated:
    default: blue-dot
    focused: blue-pin
  Subway:
    default: orange-dot
    focused: orange-pin

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  yellow-dot:
    iconUrl: /static/css/images/markers/dot-dbcf2c.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  yellow-pin:
    iconUrl: /static/css/images/markers/marker-dbcf2c.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  river-dot:
    iconUrl: /static/css/images/markers/dot-2654d2.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  river-pin:
    iconUrl: /static/css/images/markers/marker-2654d2.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  blue-dot:
    iconUrl: /static/css/images/markers/dot-0d85e9.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  blue-pin:
    iconUrl: /static/css/images/markers/marker-0d85e9.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  green-dot:
    iconUrl: /static/css/images/markers/dot-4bbd45.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  green-pin:
    iconUrl: /static/css/images/markers/marker-4bbd45.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  red-dot:
    iconUrl: /static/css/images/markers/dot-e1264d.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red-pin:
    iconUrl: /static/css/images/markers/marker-e1264d.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  orange-dot:
    iconUrl: /static/css/images/markers/dot-f95016.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  orange-pin:
    iconUrl: /static/css/images/markers/marker-f95016.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  purple-dot:
    iconUrl: /static/css/images/markers/dot-a542e5.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  purple-pin:
    iconUrl: /static/css/images/markers/marker-a542e5.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  gray-dot:
    iconUrl: /static/css/images/markers/dot-rr-color.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  gray-pin:
    iconUrl: /static/css/images/markers/marker-rr-color.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41
  nj-dot:
    iconUrl: /static/css/images/markers/dot-fa307d.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  nj-pin:
    iconUrl: /static/css/images/markers/marker-fa307d.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41

place:
  adding_supported: false
  add_button_label: Add an Place
  action_text: updated
  anonymous_name: Someone
  submit_button_label: Submit

survey:
  submission_type: surveys

  # Response display config
  show_responses: true
  response_name: response
  response_plural_name: responses
  action_text: added input on
  anonymous_name: Someone

  # Survey form config
  title: Add your input
  form_link_text: Respond to the survey
  submit_btn_text: Send
  items:
    - prompt: I bike to this station
      label: I bike to this station
      name: i_bike_here
      type: select
      options:
        - Never
        - Daily
        - A few times a week
        - A few times a month
    - prompt: I think this station
      label: I think this station
      name: my_thoughts_about_station
      type: select
      options:
        - Has sufficient and good quality bike parking
        - Needs more bike parking
        - Needs better parking (covered, sheltered, secure, ...)
    - prompt: I would bike to this station if improvements were made
      label: I would bike to this station if improvements were made
      name: i_would_bike_here
      type: checkbox
      attrs:
        - key: value
          value: I would bike to this station if improvements were made.
    - prompt: Please share your other ideas
      label: Other thoughts
      name: other_thoughts
      type: textarea
      attrs:
        - key: placeholder
          value: Are there gaps in the road and trail network around this station that you think need to be addressed with things like new bike lanes, shoulders, or trails? Are there other specific problems that prevent you or others from biking to this station?
    - prompt: Your Name
      type: text
      name: submitter_name
      optional: true

support:
  submission_type: bicyclists
  submit_btn_text: I would bike to this station if improvements were made
  action_text: would bike to
  anonymous_name: Someone

pages:
  - title: About
    slug: about
    start_page: true
  - title: Disclaimer
    slug: disclaimer
